### ISSUE TITLE
Does not automatically play on mobile browsers (iPhone, iPad)

### ISSUE THREAD

**Issue by csling** [PoliticalPenguin/politicalpenguin#73]

**Comment by RandomSeeded** [comment]
This is out of our control I'm afraid, from the Safari docs:

Warning: To prevent unsolicited downloads over cellular networks at the user’s expense, embedded media cannot be played automatically in Safari on iOS—the user always initiates playback. A controller is automatically supplied on iPhone or iPod touch once playback in initiated, but for iPad you must either set the controls attribute or provide a controller using JavaScript.

**Comment by RandomSeeded** [comment]
Also true for Android.
